### ISSUE TITLE
utube command name clash with omer73364's utube

### ISSUE THREAD

**Issue by Veraellyunjie** [Hetari/pyutube#1]
> ## [Inspiration](https://github.com/Hetari/pyutube#inspiration)
> This project was inspired by [uTube](https://github.com/omer73364/uTube/)

Both projects provide `utube` command, so no straightforward way to install both globally

**Comment by Hetari** [comment]
Thank you for bringing this to our attention. I understand the concern regarding both projects' conflicting `utube` commands. I will fix it soon by replacing the `utube` command with the `pyutube` command, ensuring that users can utilize both tools globally without conflicts.

Please make sure to watch the repository so that you can stay updated on any changes. If you have any more questions or concerns, please don't hesitate to let me know. Your feedback is valuable in improving the project experience for everyone.

**Thank you for your understanding and support.** 😊

**Comment by Hetari** [comment]
New release 😁

Change the endpoint into `pyutube`. see the `readme.md` for more information 👍

**Comment by Hetari** [comment]
New release 😁

Change the endpoint into `pyutube`. see the `readme.md` for more information 👍
