### ISSUE TITLE
playlist didn't downlaod 

### ISSUE THREAD

**Issue by abdulsalam111** [Hetari/pyutube#12]
I get this error when i try to download a video 
DownloadService_stdout: 2024-09-25 12:27:28,105 >>> An error occurred. Please report this issue to the support team by creating an issue on GitHub at https://github.com/hetari/pyutube/issues. Include the 'error.log' file located at C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\pyutube\services\error.log.

**Comment by Hetari** [comment]
# 🎉 Issue Fixed: Download Error in PyUtube!

Hey @abdulsalam111 ,

Thanks so much for bringing up the download issue with **PyUtube**! I really appreciate your help in making the project better.

### Good News!
I found out that the problem was due to a bug in the newer version of the library. I’ve reverted to version **1.3.24**, and that seems to do the trick! 

### What You Can Do:
If you’re still having trouble, you can install version **1.3.24** with this command:

```bash
pip install --upgrade pyutube
```
and make sure that the version is `1.3.24` or above by running:
```bash
pyutube -v
```

If you have any other questions or run into more issues, don’t hesitate to reach out. I'm here to help!

Thanks again, and happy downloading! 🎥
