### ISSUE TITLE
Unterminated string literal

### ISSUE THREAD

**Issue by jiagengliu** [Hetari/pyutube#9]
Hello, I'm using Python 3.11.5 on a Windows-based Ubuntu WSL and got the following error: 

```
$ pyutube cMPnY7EuZvo -v
Traceback (most recent call last):
  File "/home/jiageng/anaconda3/bin/pyutube", line 5, in <module>
    from pyutube import cli
  File "/home/jiageng/anaconda3/lib/python3.11/site-packages/pyutube/__init__.py", line 13, in <module>
    from .cli import app
  File "/home/jiageng/anaconda3/lib/python3.11/site-packages/pyutube/cli.py", line 244
    console.print(f"All playlist are already downloaded in this directory, see '{
                  ^
SyntaxError: unterminated string literal (detected at line 244)
```

**Comment by Hetari** [comment]
Hi @jiagengliu,

Thank you for reporting this issue. The error you encountered was due to an unterminated string literal in the `cli.py` file. The problem was solved in version 1.3.0 of the project.

Please update to the latest version by running the following command:

```sh
pip install --upgrade pyutube
```
This should resolve the error you encountered. If you have any further issues or feature requests, feel free to let me know.
